language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
dist: xenial
branches:
  only:
  - master
before_install:
  - sudo apt-get update && sudo apt-get build-dep python-imaging
  - sudo service postgresql restart
install:
  - pip install tox-travis
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
services:
  - postgresql
before_script:
  - psql template1 -c "create extension hstore;"
  - psql template1 -c "create extension postgis;"
  - psql template1 -c "create extension citext;"
script:
  - tox -v
