language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
dist: xenial
branches:
  only:
  - master
install:
  - pip install tox-travis
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11-postgis-2.5
services:
  - postgresql
before_script:
  - psql template1 -c "create extension hstore;"
  - psql template1 -c "create extension postgis;"
  - psql template1 -c "create extension citext;"
script:
  - tox
